### PR TITLE
not less than 30s? (correct me if i'm wrong)

### PR DESCRIPTION
**Pull request by ImprovedTube**
thanks

https://developer.chrome.com/blog/longer-esw-lifetimes

### CODE REVIEW

**Comment by guest271314** [comment]
Not sure what the question is?

**Comment by guest271314** [comment]
@ImprovedTube 

> - The service worker terminates if a single request, such as an event or API call, takes longer than 5 minutes to process.
>
> Some APIs like native messaging provide a strong keep-alive which cancel both of these timers.

`"externally_connectable"` is within that exception range. Both the code in the repository and your patch work as intended on Chromium Version 122.0.6206.0 (Developer Build) (64-bit).

**Comment by guest271314** [comment]
@ImprovedTube 

I must have had the extension window open when I tested your code. 

The code does reset now for that version.

Both the code in this repository and your patch. 

I'll run some more tests. 

Thanks.

**Comment by guest271314** [comment]
I went ahead and deleted that folder. The other options work the last time I checked. Feel free to test the other options, too.

**Comment by guest271314** [comment]
Thanks, again!

**Comment by ImprovedTube** [comment]
hey @guest271314  sorry! didnt try your code yet 🙈, simply only thought it might be <30s (or else <5minute)   
(  state of our Mf3 preparations for ~600000 users:       didnt find out where the constant 1000s of these come from:
   ```
background.js:0 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
   background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```

( everything works with mf3 but sometimes requires a reload /restart  (and this didnt make a difference "const keepAliveInterval = setInterval(() => chrome.runtime.sendMessage({ status: 'keep-alive' }), 29.5 * 1000);"   ))
  
 - hence delaying mf3 further (& sidepanel😆)

**Comment by ImprovedTube** [comment]
hey @guest271314  sorry! didnt try your code yet 🙈, simply only thought it might be <30s (or else <5minute)   

--- 

 -  (  _State of our Mf3 preparations for ~600000 users:_       didnt find out where the constant 1000s of these come from <code> background.js:0 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
   background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.  </code>
    -  everything works with mf3 but sometimes requires a reload /restart 
        -  (and this didnt make a difference "const keepAliveInterval = setInterval(() => chrome.runtime.sendMessage({ status: 'keep-alive' }), 29.5 * 1000);"   ))
          -  hence delaying mf3 further (& sidepanel😆)

**Comment by ImprovedTube** [comment]
hey @guest271314  ohh, sorry! didnt try your code yet 🙈, simply only thought it might be <30s (or else <5minute)   

--- 

 -  (  _State of our Mf3 preparations for ~600000 users:_       didnt find out where the constant 1000s of these come from <code> background.js:0 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
   background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.  </code>
    -  everything works with mf3 but sometimes requires a reload /restart 
        -  (and this didnt make a difference "const keepAliveInterval = setInterval(() => chrome.runtime.sendMessage({ status: 'keep-alive' }), 29.5 * 1000);"   ))
          -  hence delaying mf3 further (& sidepanel😆)

**Comment by guest271314** [comment]
That `"externally_connecatble"` example was the most problematic to get right. That version used to work at some point in the recent past. The other folders, each a different way to keep an MV3 `ServiceWorker` active potentially indefinitely, work as expected. 

Feel free to test any gear I publish until it breaks, or does what the README and/or comments say it is supposed to do.

**Pull request closed without merging**
